/**
 * Studio Scenes — pre-built desktop UIs the user customizes via slots
 * (text fields, colors). Each scene's `compile(slots)` returns a complete
 * file map (main.js, index.html, package.json, etc.) that the template
 * generator writes directly to the workspace. The result is a real
 * Electron project that builds to .exe.
 *
 * Adding a scene = add an entry below. Each scene is self-contained;
 * adding new ones doesn't change existing behavior.
 *
 * NOT YET supported (future Level 3): drag-drop component placement,
 * dynamic data binding, plugin runtime. The slot model is intentionally
 * the foundation those would extend rather than replace.
 */

export type SlotKind = "text" | "longText" | "color";

export interface Slot {
  key: string;
  label: string;
  kind: SlotKind;
  default: string;
  helper?: string;
}

export interface Scene {
  id: string;
  name: string;
  tagline: string;
  /** Two-tone gradient + glyph for the picker card. */
  grad: [string, string];
  glyph: string;
  /** Slot definitions in display order. */
  slots: readonly Slot[];
  /** Compile this scene with the given slot values into a file map.
   *  Map keys are relative paths inside the project workspace. */
  compile: (values: Record<string, string>) => Record<string, string>;
}

const escapeHtml = (s: string) =>
  String(s).replace(/[&<>"']/g, (c) => ({
    "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;",
  } as const)[c]!);

const escapeJsString = (s: string) =>
  String(s).replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$/g, "\\$");

/**
 * Common Electron main.js shared by all scenes — opens index.html, applies
 * window dimensions from config.json. Scenes can override by providing
 * their own main.js in compile().
 */
function commonMainJs(productName: string, width: number, height: number): string {
  return `const { app, BrowserWindow } = require("electron");
const path = require("node:path");

let win = null;
function create() {
  win = new BrowserWindow({
    width: ${width},
    height: ${height},
    minWidth: 480,
    minHeight: 320,
    title: ${JSON.stringify(productName)},
    backgroundColor: "#0b0b0d",
    autoHideMenuBar: true,
    show: false,
    icon: require("node:fs").existsSync(path.join(__dirname, "icon.png"))
      ? path.join(__dirname, "icon.png")
      : undefined,
    webPreferences: {
      preload: path.join(__dirname, "preload.js"),
      contextIsolation: true,
      nodeIntegration: false,
    },
  });
  win.loadFile(path.join(__dirname, "index.html"));
  win.once("ready-to-show", () => win.show());
}
app.whenReady().then(create);
app.on("window-all-closed", () => { if (process.platform !== "darwin") app.quit(); });
app.on("activate", () => { if (BrowserWindow.getAllWindows().length === 0) create(); });
`;
}

const commonPreloadJs = `const { contextBridge } = require("electron");
contextBridge.exposeInMainWorld("api", {
  // Add IPC bridge functions here as you wire up more main-process features.
});
`;

function pkgJson(productName: string): Record<string, unknown> {
  const safeName = productName.toLowerCase().replace(/[^a-z0-9-]+/g, "-").replace(/^-+|-+$/g, "") || "scene-app";
  return {
    name: safeName,
    productName,
    version: "1.0.0",
    description: `Generated by WebToDesktop Builder`,
    main: "main.js",
    scripts: { start: "electron ." },
    devDependencies: {
      electron: "^33.2.0",
      "electron-builder": "^25.1.8",
    },
    build: {
      appId: `com.webtodesktop.scene.${safeName}`,
      productName,
      directories: { output: "dist" },
      files: ["main.js", "preload.js", "index.html", "config.json", "icon.*", "package.json"],
      win: { target: "nsis" },
      mac: { target: "dmg" },
      linux: { target: "AppImage" },
    },
  };
}

/* ─────────── SCENES ─────────── */

const WELCOME: Scene = {
  id: "welcome",
  name: "Welcome screen",
  tagline: "Hero with title, tagline, and a primary action button",
  grad: ["#5b9dff", "#a78bfa"],
  glyph: "✦",
  slots: [
    { key: "title",        label: "Title",          kind: "text",     default: "Welcome",                                helper: "Main hero headline" },
    { key: "tagline",      label: "Tagline",        kind: "longText", default: "Your custom desktop app, built in minutes." },
    { key: "buttonLabel",  label: "Button label",   kind: "text",     default: "Get started" },
    { key: "footer",       label: "Footer text",    kind: "text",     default: "Made with WebToDesktop Builder" },
    { key: "accent",       label: "Accent color",   kind: "color",    default: "#5b9dff" },
    { key: "accent2",      label: "Accent (2)",     kind: "color",    default: "#a78bfa" },
    { key: "bg",           label: "Background",     kind: "color",    default: "#0b0b0d" },
  ],
  compile: (s) => ({
    "main.js":     commonMainJs(s.title || "Welcome", 1100, 760),
    "preload.js":  commonPreloadJs,
    "package.json": JSON.stringify(pkgJson(s.title || "Welcome"), null, 2) + "\n",
    "config.json":  JSON.stringify({ name: s.title || "Welcome" }, null, 2) + "\n",
    "index.html": `<!doctype html>
<html lang="en"><head>
<meta charset="UTF-8" />
<meta http-equiv="Content-Security-Policy" content="default-src 'self'; style-src 'self' 'unsafe-inline'; script-src 'self'" />
<title>${escapeHtml(s.title || "Welcome")}</title>
<style>
  :root { --accent: ${s.accent || "#5b9dff"}; --accent2: ${s.accent2 || "#a78bfa"}; --bg: ${s.bg || "#0b0b0d"}; }
  * { box-sizing: border-box; margin: 0; padding: 0; }
  html, body { height: 100%; background: var(--bg); color: #f5f5f7; font: 14px -apple-system, "Segoe UI", system-ui, sans-serif; user-select: none; }
  .app {
    height: 100%; display: grid; place-items: center; padding: 32px;
    background:
      radial-gradient(60% 50% at 0% 0%,   color-mix(in srgb, var(--accent)  18%, transparent) 0%, transparent 60%),
      radial-gradient(60% 50% at 100% 100%, color-mix(in srgb, var(--accent2) 18%, transparent) 0%, transparent 60%),
      var(--bg);
  }
  .card { max-width: 560px; width: 100%; text-align: center; padding: 36px; }
  h1 { font-size: 36px; font-weight: 700; letter-spacing: -0.02em;
       background: linear-gradient(135deg, var(--accent), var(--accent2));
       -webkit-background-clip: text; background-clip: text; color: transparent; }
  .tagline { color: rgba(245,245,247,0.65); margin-top: 12px; font-size: 16px; line-height: 1.5; }
  button.primary {
    margin-top: 28px; padding: 14px 28px; border: 0; border-radius: 10px;
    background: linear-gradient(135deg, var(--accent), var(--accent2));
    color: white; font-size: 14px; font-weight: 600; letter-spacing: 0.02em; cursor: default;
    transition: filter 100ms, transform 100ms;
  }
  button.primary:hover  { filter: brightness(1.1); }
  button.primary:active { transform: translateY(1px); }
  .footer { position: fixed; bottom: 16px; left: 0; right: 0; text-align: center;
            color: rgba(245,245,247,0.4); font-size: 11px; letter-spacing: 0.04em; }
</style></head>
<body>
  <div class="app">
    <div class="card">
      <h1>${escapeHtml(s.title || "Welcome")}</h1>
      <p class="tagline">${escapeHtml(s.tagline || "")}</p>
      <button class="primary" id="cta">${escapeHtml(s.buttonLabel || "Get started")}</button>
    </div>
  </div>
  <div class="footer">${escapeHtml(s.footer || "")}</div>
  <script>
    document.getElementById("cta").addEventListener("click", () => {
      // Wire your main action here. Replace with API calls, navigation, etc.
      const card = document.querySelector(".card");
      card.animate([{ transform: "scale(1)" }, { transform: "scale(1.02)" }, { transform: "scale(1)" }], { duration: 220 });
    });
  </script>
</body></html>
`,
  }),
};

const NOTE_EDITOR: Scene = {
  id: "note-editor",
  name: "Note editor",
  tagline: "Sidebar with notes list + main writing pane (localStorage-backed)",
  grad: ["#10b981", "#0ea5e9"],
  glyph: "✎",
  slots: [
    { key: "title",       label: "App title",     kind: "text",  default: "Notes",  helper: "Shown in the sidebar header" },
    { key: "placeholder", label: "Empty state",   kind: "text",  default: "Start typing…" },
    { key: "accent",      label: "Accent color",  kind: "color", default: "#10b981" },
    { key: "bg",          label: "Background",    kind: "color", default: "#0d1117" },
    { key: "surface",     label: "Surface",       kind: "color", default: "#161b22" },
  ],
  compile: (s) => ({
    "main.js":     commonMainJs(s.title || "Notes", 1280, 800),
    "preload.js":  commonPreloadJs,
    "package.json": JSON.stringify(pkgJson(s.title || "Notes"), null, 2) + "\n",
    "config.json":  JSON.stringify({ name: s.title || "Notes" }, null, 2) + "\n",
    "index.html": `<!doctype html>
<html lang="en"><head>
<meta charset="UTF-8" />
<meta http-equiv="Content-Security-Policy" content="default-src 'self'; style-src 'self' 'unsafe-inline'; script-src 'self'" />
<title>${escapeHtml(s.title || "Notes")}</title>
<style>
  :root { --accent: ${s.accent || "#10b981"}; --bg: ${s.bg || "#0d1117"}; --surface: ${s.surface || "#161b22"}; --border: rgba(255,255,255,0.08); --text: #f5f5f7; --muted: rgba(245,245,247,0.55); }
  * { box-sizing: border-box; margin: 0; padding: 0; }
  html, body { height: 100%; background: var(--bg); color: var(--text); font: 14px -apple-system, "Segoe UI", system-ui, sans-serif; }
  .shell { display: grid; grid-template-columns: 260px 1fr; height: 100%; }
  .sidebar { background: var(--surface); border-right: 1px solid var(--border); display: flex; flex-direction: column; }
  .sidebar h1 { padding: 16px; font-size: 14px; font-weight: 600; border-bottom: 1px solid var(--border); display: flex; align-items: center; justify-content: space-between; user-select: none; }
  .sidebar h1 button { background: var(--accent); color: white; border: 0; padding: 4px 10px; border-radius: 6px; font: inherit; cursor: default; font-size: 12px; }
  .sidebar h1 button:hover { filter: brightness(1.1); }
  .notes { flex: 1; overflow-y: auto; padding: 8px; }
  .note-item { padding: 10px 12px; border-radius: 8px; cursor: default; user-select: none; }
  .note-item:hover { background: rgba(255,255,255,0.04); }
  .note-item.active { background: color-mix(in srgb, var(--accent) 18%, transparent); }
  .note-item .preview { color: var(--muted); font-size: 12px; margin-top: 2px; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
  .editor { padding: 24px 32px; display: flex; flex-direction: column; }
  .editor textarea { flex: 1; background: transparent; border: 0; outline: 0; resize: none; color: var(--text); font: 15px/1.6 -apple-system, "Segoe UI", system-ui, sans-serif; }
  .empty { color: var(--muted); display: grid; place-items: center; height: 100%; }
</style></head>
<body>
<div class="shell">
  <aside class="sidebar">
    <h1>${escapeHtml(s.title || "Notes")} <button id="new">+ New</button></h1>
    <div class="notes" id="list"></div>
  </aside>
  <main class="editor" id="main">
    <div class="empty" id="empty">Pick a note or create a new one.</div>
    <textarea id="text" style="display:none" placeholder="${escapeHtml(s.placeholder || "Start typing…")}"></textarea>
  </main>
</div>
<script>
  const KEY = "scene-notes-v1";
  let notes = JSON.parse(localStorage.getItem(KEY) || "[]");
  let activeId = notes[0]?.id ?? null;

  const listEl  = document.getElementById("list");
  const textEl  = document.getElementById("text");
  const emptyEl = document.getElementById("empty");

  function save() { localStorage.setItem(KEY, JSON.stringify(notes)); }
  function render() {
    listEl.innerHTML = "";
    for (const n of notes) {
      const div = document.createElement("div");
      div.className = "note-item" + (n.id === activeId ? " active" : "");
      div.innerHTML = '<div>' + (n.title || "Untitled").replace(/[<>&]/g, c => ({'<':'&lt;','>':'&gt;','&':'&amp;'}[c])) + '</div><div class="preview">' + (n.body || "").slice(0, 60).replace(/[<>&]/g, c => ({'<':'&lt;','>':'&gt;','&':'&amp;'}[c])) + '</div>';
      div.addEventListener("click", () => { activeId = n.id; openActive(); });
      listEl.appendChild(div);
    }
    openActive();
  }
  function openActive() {
    const n = notes.find(x => x.id === activeId);
    if (!n) { emptyEl.style.display = "grid"; textEl.style.display = "none"; return; }
    emptyEl.style.display = "none"; textEl.style.display = "block";
    textEl.value = n.body || "";
    textEl.focus();
  }
  textEl.addEventListener("input", () => {
    const n = notes.find(x => x.id === activeId); if (!n) return;
    n.body = textEl.value;
    n.title = (textEl.value.split("\\n")[0] || "Untitled").slice(0, 60);
    save();
    // Update only the active item's preview, no full re-render to keep focus.
    const item = listEl.querySelector(".note-item.active");
    if (item) item.innerHTML = '<div>' + n.title.replace(/[<>&]/g, c => ({'<':'&lt;','>':'&gt;','&':'&amp;'}[c])) + '</div><div class="preview">' + (n.body || "").slice(0, 60).replace(/[<>&]/g, c => ({'<':'&lt;','>':'&gt;','&':'&amp;'}[c])) + '</div>';
  });
  document.getElementById("new").addEventListener("click", () => {
    const n = { id: Date.now().toString(36), title: "Untitled", body: "" };
    notes.unshift(n); activeId = n.id; save(); render();
  });
  render();
</script>
</body></html>
`,
  }),
};

export const STUDIO_SCENES: Scene[] = [WELCOME, NOTE_EDITOR];

export const STUDIO_SCENES_BY_ID: Record<string, Scene> = Object.fromEntries(
  STUDIO_SCENES.map((s) => [s.id, s]),
);
