import type { Theme } from "./types";

/**
 * Translate a Theme into a flat record of CSS custom properties. The same
 * record is consumed by:
 *   - the in-builder PreviewWindow (passed to React via inline style)
 *   - the generated app's chrome.html (written to theme.css at build time)
 *
 * Variable names are namespaced with `--w2a-` so they never collide with
 * styles a wrapped website might define.
 */
export function themeToCssVars(theme: Theme): Record<string, string> {
  const blurPx = Math.round(theme.glass * 0.24);             // 0..24px
  const surfaceAlpha = (1 - theme.glass / 200).toFixed(2);   // 0.5..1.0
  const shadowMap = ["none", SHADOW_1, SHADOW_2, SHADOW_3];
  const animation = ANIM[theme.animation];

  return {
    "--w2a-bg":            theme.colors.bg,
    "--w2a-surface":       theme.colors.surface,
    "--w2a-surface-alpha": surfaceAlpha,
    "--w2a-titlebar":      theme.colors.titlebar,
    "--w2a-accent":        theme.colors.accent,
    "--w2a-accent-2":      theme.colors.accent2,
    "--w2a-text":          theme.colors.text,
    "--w2a-text-muted":    theme.colors.textMuted,
    "--w2a-border":        theme.colors.border,
    "--w2a-light-close":   theme.colors.lights.close,
    "--w2a-light-min":     theme.colors.lights.min,
    "--w2a-light-max":     theme.colors.lights.max,

    "--w2a-radius":         `${theme.radius}px`,
    "--w2a-radius-sm":      `${Math.max(0, theme.radius - 4)}px`,
    "--w2a-radius-lg":      `${theme.radius + 4}px`,
    "--w2a-titlebar-h":     `${theme.titleBarHeight}px`,
    "--w2a-blur":           `${blurPx}px`,
    "--w2a-shadow":         shadowMap[Math.max(0, Math.min(3, theme.shadow))],
    "--w2a-anim-curve":     animation.curve,
    "--w2a-anim-duration":  animation.duration,
    "--w2a-font":           theme.font ?? "-apple-system, system-ui, sans-serif",
    "--w2a-density":        DENSITY[theme.density],
    /* Quoted string — chrome.html reads this at runtime to flip its layout. */
    "--w2a-frame":          `"${theme.windowFrame}"`,
  };
}

/**
 * Render the CSS variables as a `:root { ... }` stylesheet body. Used by the
 * template generator to write `theme.css` into the workspace.
 */
export function themeToCss(theme: Theme): string {
  const vars = themeToCssVars(theme);
  const lines = Object.entries(vars).map(([k, v]) => `  ${k}: ${v};`).join("\n");
  return [
    `/* Auto-generated by WebToDesktop Builder — theme: ${theme.name} (${theme.id}) */`,
    `:root {`,
    lines,
    `}`,
    "",
    BACKGROUND_RULES[theme.background],
    "",
    FRAME_RULES[theme.windowFrame],
  ].join("\n");
}

/** Convert the CSS-vars record into an inline style for React. */
export function themeToReactStyle(theme: Theme): React.CSSProperties {
  return themeToCssVars(theme) as unknown as React.CSSProperties;
}

const SHADOW_1 = "0 1px 2px rgba(0,0,0,0.2)";
const SHADOW_2 = "0 8px 24px -8px rgba(0,0,0,0.4), 0 2px 4px rgba(0,0,0,0.2)";
const SHADOW_3 = "0 24px 64px -12px rgba(0,0,0,0.6), 0 4px 12px rgba(0,0,0,0.3)";

const ANIM = {
  smooth:  { curve: "cubic-bezier(0.4, 0, 0.2, 1)",      duration: "200ms" },
  snappy:  { curve: "cubic-bezier(0.2, 0.8, 0.2, 1)",    duration: "120ms" },
  bouncy:  { curve: "cubic-bezier(0.34, 1.56, 0.64, 1)", duration: "320ms" },
  none:    { curve: "linear",                            duration: "0ms"   },
} as const;

const DENSITY = {
  compact:     "0.85",
  comfortable: "1",
  spacious:    "1.15",
} as const;

const BACKGROUND_RULES: Record<Theme["background"], string> = {
  solid: `body { background: var(--w2a-bg); }`,
  gradient: `body {
  background:
    radial-gradient(80% 50% at 0% 0%,   color-mix(in srgb, var(--w2a-accent)   12%, transparent) 0%, transparent 60%),
    radial-gradient(80% 50% at 100% 100%, color-mix(in srgb, var(--w2a-accent-2) 10%, transparent) 0%, transparent 60%),
    var(--w2a-bg);
}`,
  mesh: `body {
  background:
    radial-gradient(60% 40% at 10% -10%, color-mix(in srgb, var(--w2a-accent-2) 22%, transparent) 0%, transparent 60%),
    radial-gradient(45% 35% at 100% 0%,  color-mix(in srgb, var(--w2a-accent)   16%, transparent) 0%, transparent 60%),
    radial-gradient(50% 45% at 50% 110%, color-mix(in srgb, var(--w2a-accent)   12%, transparent) 0%, transparent 60%),
    var(--w2a-bg);
}`,
  image: `body { background: var(--w2a-bg); }`,
};

const FRAME_RULES: Record<Theme["windowFrame"], string> = {
  macos: `/* frame: macOS — traffic lights left, title centered */`,
  windows11: `/* frame: Windows 11 — controls right, mica-style glass */`,
  unified: `/* frame: unified — title bar continuous with content */`,
  frameless: `/* frame: frameless — minimal chrome */`,
};
